# Generated by Django 4.1 on 2022-09-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newslettersignup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersignup',
            name='user',
        ),
    ]
