# Generated by Django 3.2.13 on 2022-07-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220720_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='default_phone_number',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='l_name',
        ),
    ]
