# Generated by Django 3.2.13 on 2022-07-20 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20220720_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='userDetail',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='userDetail',
        ),
        migrations.AddField(
            model_name='basket',
            name='user_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='user_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
