# Generated by Django 4.1.1 on 2022-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_customerinfo_customer_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='company',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='county',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='postcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
