# Generated by Django 3.2.13 on 2022-07-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220720_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketOrderItems',
            new_name='BasketItems',
        ),
    ]
