# Generated by Django 4.1.1 on 2022-10-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customerinfo_company_alter_customerinfo_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='basketitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customerinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
        migrations.DeleteModel(
            name='BasketItems',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
