# Generated by Django 3.2.13 on 2022-07-21 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_auto_20220721_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='country',
            field=django_countries.fields.CountryField(default='Country'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='county',
            field=models.CharField(blank=True, default='County, Province or State', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.basket'),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='phone_number',
            field=models.CharField(default='Phone Number', max_length=20),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='postcode',
            field=models.CharField(blank=True, default='Post Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='street_address1',
            field=models.CharField(default='Street Address 1', max_length=80),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='street_address2',
            field=models.CharField(blank=True, default='Street Address 2', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customerinfo',
            name='town_or_city',
            field=models.CharField(default='Town or City', max_length=40),
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
    ]
