# Generated by Django 3.2.13 on 2022-07-21 21:33

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220721_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='country',
            field=django_countries.fields.CountryField(default='Country', max_length=80),
        ),
    ]
