# Generated by Django 3.2.13 on 2022-07-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customerinfo_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitems',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, max_length=150),
        ),
    ]
