# Generated by Django 3.2.13 on 2022-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_basketitems_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='company',
            field=models.CharField(default='Company', max_length=80),
        ),
    ]
